# Generated by Django 5.0 on 2024-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akyc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
